import { createHash, generateKeyPairSync, randomUUID } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

import { createEffectState, EffectRunner, FakeGoogleCalendarPort } from "../../../src/application/effects";
import type { LocalStateV1, NormalizedTaskV1, ProposalV1 } from "../../../src/contracts/v1";
import { encryptToken } from "../../../src/server/security/crypto";
import { createLiveConnectorRuntime, liveConnectorConfiguration, resetLiveConnectorRuntimeForTests } from "../../../src/server/connectors/live-runtime";
import { LocalStore } from "../../../src/storage/local-store/local-store";

const directories:string[]=[];
const directory=async()=>{const value=await mkdtemp(join(tmpdir(),"live-connectors-"));directories.push(value);return value;};
afterEach(async()=>{vi.restoreAllMocks();await Promise.all(directories.splice(0).map((value)=>rm(value,{recursive:true,force:true})));});

const PROFILE=randomUUID(),TASK=randomUUID(),PROPOSAL=randomUUID(),RESULT=randomUUID(),NOW="2026-07-23T15:00:00Z";
const freshness={schemaVersion:1 as const,fetchedAt:NOW,sourceUpdatedAt:null,expiresAt:null,state:"fresh" as const};
const task:NormalizedTaskV1={schemaVersion:1,id:TASK,source:"local",sourceEntityId:"local-task",title:"Focus",state:"open",durationMinutes:60,deadlineAt:null,priority:1,projectRef:null,labels:[],immutable:false,provenance:{schemaVersion:1,source:"local",sourceEntityId:"local-task",consentRevision:0,freshness,importedAt:NOW}};
const proposal:ProposalV1={schemaVersion:1,id:PROPOSAL,taskId:TASK,sourceRevision:0,startAt:"2026-07-23T16:00:00Z",endAt:"2026-07-23T17:00:00Z",score:80,breakdown:{capacityFit:40,deadlineUrgency:10,goalAlignment:10,contextSwitch:10,recoverySupport:10},confidence:.8,limitations:[],status:"approved"};
const initial=():LocalStateV1=>({schemaVersion:1,revision:0,profileId:PROFILE,timeZone:"America/Chicago",connections:{},tasks:[task],schedulingIntents:[],commitments:[],observations:[],proposals:[proposal],events:[],commandReceipts:{}});
const command=(expectedRevision:number,idempotencyKey=`key-${expectedRevision}`)=>({expectedRevision,commandId:randomUUID(),idempotencyKey,resultId:RESULT});
const envelope=async(runtime:NonNullable<ReturnType<typeof createLiveConnectorRuntime>>,value:object)=>encryptToken(JSON.stringify(value),{...await runtime.keys.load(),createdAt:NOW});
const env=(root:string,privateKey="-----BEGIN PRIVATE KEY-----\nplaceholder\n-----END PRIVATE KEY-----")=>({CONNECTORS_ENABLED:"1",APP_ORIGIN:"http://127.0.0.1:3000",APP_SESSION_SECRET:"session-secret",APP_CSRF_SECRET:"csrf-secret",CONNECTOR_STATE_PATH:join(root,"state.json"),APP_DATA_KEY_PATH:join(root,"key.json"),GMAIL_ADDON_ENABLED:"1",GOOGLE_CLIENT_ID:"google-id",GOOGLE_CLIENT_SECRET:"google-secret",GOOGLE_REDIRECT_URI:"http://127.0.0.1:3000/api/v1/oauth/google/callback",LINEAR_CLIENT_ID:"linear-id",LINEAR_CLIENT_SECRET:"linear-secret",LINEAR_REDIRECT_URI:"http://127.0.0.1:3000/api/v1/oauth/linear/callback",GITHUB_APP_SLUG:"capacity-scheduler",GITHUB_APP_ID:"42",GITHUB_APP_PRIVATE_KEY:privateKey,GITHUB_REDIRECT_URI:"http://127.0.0.1:3000/api/v1/oauth/github/callback",GITHUB_REPOSITORIES:"example/project"});
const response=(value:unknown,status=200)=>{const body=JSON.stringify(value);return new Response(body,{status,headers:{"content-type":"application/json","content-length":String(Buffer.byteLength(body))}});};

describe("atomic live connector store",()=>{
  it("atomically revokes tokens, effects, source receipts, and dependents across restart",async()=>{const root=await directory(),runtime=createLiveConnectorRuntime(env(root),async()=>response({}))!;await runtime.store.initialize(initial());
    await runtime.store.commitConnectorToken({...command(0,"connect"),source:"google-calendar",envelope:await envelope(runtime,{accessToken:"token",refreshToken:"refresh",expiresIn:3600,scope:["calendar.read","calendar.event.write"]}),consentRevision:1,capabilities:["calendar.read","calendar.event.write"],connectedAt:NOW});
    const intent={effectId:randomUUID(),proposalId:PROPOSAL,marker:"",provider:"google-calendar" as const};intent.marker=`capacity-effect:${intent.effectId}`;await runtime.store.commitConnectorEffect({...command(1,"effect"),state:createEffectState(intent)});
    const receipt=await runtime.store.revokeConnectorSource({...command(2,"revoke"),source:"google-calendar",consentRevision:2,at:"2026-07-23T16:00:00Z"});expect(receipt).toMatchObject({localTokenDeleted:true,removed:{effects:1,connectors:1,receipts:2}});
    const restarted=new LocalStore(join(root,"state.json"));expect(await restarted.loadConnectorToken("google-calendar")).toBeNull();expect(await restarted.loadConnectorEffect(intent.effectId)).toBeNull();expect(Object.keys((await restarted.load()).commandReceipts)).toHaveLength(1);
    await expect(restarted.revokeConnectorSource({...command(3,"other"),commandId:command(0).commandId,source:"google-calendar",consentRevision:3,at:"not-an-instant"})).rejects.toThrow("INVALID_COMMAND");
  });

  it("rejects stale consent, cross-command idempotency reuse, and unauthorized effects before mutation",async()=>{const root=await directory(),runtime=createLiveConnectorRuntime(env(root),async()=>response({}))!;await runtime.store.initialize(initial());const token=await envelope(runtime,{accessToken:"token"}),first=command(0,"same-key");
    await runtime.store.commitConnectorToken({...first,source:"google-calendar",envelope:token,consentRevision:5,capabilities:["calendar.read"],connectedAt:NOW});
    await expect(runtime.store.revokeConnectorSource({...command(1),source:"google-calendar",consentRevision:5,at:"2026-07-23T16:00:00Z"})).rejects.toThrow("STALE_CONSENT_REVISION");expect(await runtime.store.loadConnectorToken("google-calendar")).not.toBeNull();
    await expect(runtime.store.commitConnectorToken({...command(1,"same-key"),source:"linear",envelope:token,consentRevision:1,capabilities:["task.connect","task.read","task.sync","task.revoke"],connectedAt:NOW})).rejects.toThrow("IDEMPOTENCY_MISMATCH");
    const effectId=randomUUID();await expect(runtime.store.commitConnectorEffect({...command(1),state:createEffectState({effectId,proposalId:PROPOSAL,marker:`capacity-effect:${effectId}`,provider:"google-calendar"})})).rejects.toThrow("GOOGLE_CALENDAR_WRITE_NOT_AUTHORIZED");expect((await runtime.store.load()).revision).toBe(1);
  });

  it("binds an approved proposal to one effect and permits only append-only state transitions",async()=>{const root=await directory(),runtime=createLiveConnectorRuntime(env(root),async()=>response({}))!;await runtime.store.initialize(initial());const connect=command(0,"connect");await runtime.store.commitConnectorToken({...connect,source:"google-calendar",envelope:await envelope(runtime,{accessToken:"token"}),consentRevision:1,capabilities:["calendar.event.write"],connectedAt:NOW});
    const effectId=randomUUID(),intent={effectId,proposalId:PROPOSAL,marker:`capacity-effect:${effectId}`,provider:"google-calendar" as const},pending=createEffectState(intent),succeeded=(await new EffectRunner(new FakeGoogleCalendarPort([{outcome:"succeeded",marker:intent.marker,providerEntityId:"event-1"}])).execute(intent,pending)).state;
    await expect(runtime.store.commitConnectorEffect({...connect,state:pending})).rejects.toThrow("INVALID_EFFECT_STATE");
    await expect(runtime.store.commitConnectorEffect({...command(1,"fabricated"),state:succeeded})).rejects.toThrow("INVALID_EFFECT_PROPOSAL");expect((await runtime.store.load()).revision).toBe(1);
    await runtime.store.commitConnectorEffect({...command(1,"effect-create"),state:pending});
    const alternateId=randomUUID();await expect(runtime.store.commitConnectorEffect({...command(2,"alternate"),state:createEffectState({effectId:alternateId,proposalId:PROPOSAL,marker:`capacity-effect:${alternateId}`,provider:"google-calendar"})})).rejects.toThrow("INVALID_EFFECT_PROPOSAL");
    await runtime.store.commitConnectorEffect({...command(2,"effect-success"),state:succeeded});
    const divergent=(await new EffectRunner(new FakeGoogleCalendarPort([{outcome:"timeout"}])).execute(intent,pending)).state;
    await expect(runtime.store.commitConnectorEffect({...command(3,"rewrite"),state:divergent})).rejects.toThrow("INVALID_EFFECT_STATE");expect(await runtime.store.loadConnectorEffect(effectId)).toEqual(succeeded);expect((await runtime.store.load()).revision).toBe(3);
  });

  it("clears all derived proposals and effects when any connector is revoked",async()=>{const root=await directory(),runtime=createLiveConnectorRuntime(env(root),async()=>response({}))!;await runtime.store.initialize(initial());const token=await envelope(runtime,{accessToken:"token"});
    await runtime.store.commitConnectorToken({...command(0,"google-connect"),source:"google-calendar",envelope:token,consentRevision:1,capabilities:["calendar.event.write"],connectedAt:NOW});const effectId=randomUUID();await runtime.store.commitConnectorEffect({...command(1,"effect"),state:createEffectState({effectId,proposalId:PROPOSAL,marker:`capacity-effect:${effectId}`,provider:"google-calendar"})});
    await runtime.store.commitConnectorToken({...command(2,"linear-connect"),source:"linear",envelope:token,consentRevision:1,capabilities:["task.read"],connectedAt:NOW});const receipt=await runtime.store.revokeConnectorSource({...command(3,"linear-revoke"),source:"linear",consentRevision:2,at:"2026-07-23T16:00:00Z"});
    expect(receipt.removed).toMatchObject({tasks:0,commitments:0,proposals:1,effects:1});const current=await runtime.store.load();expect(current.tasks).toEqual([task]);expect(current.proposals).toEqual([]);expect(await runtime.store.loadConnectorEffect(effectId)).toBeNull();expect(await runtime.store.loadConnectorToken("google-calendar")).not.toBeNull();
  });
});

describe("configured live provider composition",()=>{
  it("activates the default bootstrap route only under valid server configuration and authority",async()=>{const root=await directory(),environment=env(root);for(const [key,value] of Object.entries(environment))vi.stubEnv(key,value);resetLiveConnectorRuntimeForTests();try{const{POST}=await import("../../../src/app/api/v1/connectors/bootstrap/route"),request=new Request("http://127.0.0.1:3000/api/v1/connectors/bootstrap",{method:"POST",headers:{cookie:"sid=session-secret",origin:"http://127.0.0.1:3000","x-csrf-token":"csrf-secret","x-expected-revision":"0","x-command-id":randomUUID(),"idempotency-key":"bootstrap-route","x-bootstrap-confirm":"initialize-absent-store","content-type":"application/json"},body:JSON.stringify({profileId:PROFILE,timeZone:"America/Chicago"})}),result=await POST(request);expect(result.status).toBe(201);expect(await result.json()).toEqual({schemaVersion:1,revision:0,initialized:true});expect((await new LocalStore(join(root,"state.json")).load()).profileId).toBe(PROFILE);}finally{resetLiveConnectorRuntimeForTests();vi.unstubAllEnvs();}});

  it("bootstraps only an absent store after full local authority and never replaces corrupt state",async()=>{const root=await directory(),runtime=createLiveConnectorRuntime(env(root),async()=>response({}))!,authorized=new Request("http://127.0.0.1:3000/api/v1/connectors/bootstrap",{method:"POST",headers:{cookie:"sid=session-secret",origin:"http://127.0.0.1:3000","x-csrf-token":"csrf-secret","x-expected-revision":"0","x-command-id":randomUUID(),"idempotency-key":"bootstrap","x-bootstrap-confirm":"initialize-absent-store"}});
    expect(runtime.authorizeBootstrap(new Request(authorized.url,{method:"POST"}))).toBeNull();await expect(readFile(join(root,"state.json"))).rejects.toThrow();expect(runtime.authorizeBootstrap(authorized)).not.toBeNull();await expect(runtime.bootstrap({profileId:PROFILE,timeZone:"America/Chicago"})).resolves.toMatchObject({initialized:true,revision:0});expect((await runtime.store.load()).profileId).toBe(PROFILE);await expect(runtime.bootstrap({profileId:randomUUID(),timeZone:"UTC"})).rejects.toThrow("STORE_ALREADY_EXISTS");
    const corruptRoot=await directory(),corruptPath=join(corruptRoot,"state.json");await writeFile(corruptPath,"corrupt",{mode:0o600});const corrupt=createLiveConnectorRuntime(env(corruptRoot),async()=>response({}))!,before=await readFile(corruptPath);expect(corrupt.authorizeBootstrap(authorized)).not.toBeNull();await expect(corrupt.bootstrap({profileId:PROFILE,timeZone:"UTC"})).rejects.toThrow("STORE_ALREADY_EXISTS");expect(await readFile(corruptPath)).toEqual(before);
  });

  it("does no store or provider work for missing or hostile mutation authority",async()=>{const root=await directory(),calls:string[]=[],runtime=createLiveConnectorRuntime(env(root),async(input)=>{calls.push(String(input));return response({});})!;const load=vi.spyOn(runtime.store,"load");
    expect(await runtime.authorizeMutation(new Request("http://127.0.0.1:3000/api/v1/sources/gmail/selected",{method:"POST",headers:{"x-gmail-addon-scope":"https://www.googleapis.com/auth/gmail.addons.current.message.readonly"}}))).toBeNull();expect(load).not.toHaveBeenCalled();expect(calls).toEqual([]);
    expect(await runtime.authorizeMutation(new Request("http://127.0.0.1:3000/api/v1/sources/google/sync",{method:"POST",headers:{cookie:"sid=session-secret",origin:"https://hostile.example","x-csrf-token":"csrf-secret","x-expected-revision":"0","x-command-id":randomUUID(),"idempotency-key":"key"}}))).toBeNull();expect(load).not.toHaveBeenCalled();expect(calls).toEqual([]);
  });

  it("persists only a confirmed selected Gmail commitment and never a raw fragment or Gmail OAuth token",async()=>{const root=await directory(),runtime=createLiveConnectorRuntime(env(root),async()=>response({}))!;await runtime.store.initialize(initial());const fragment="Hostile raw selected fragment",action={message:{id:"message-1",threadId:"thread-1",subject:"Private subject",selectedBodyFragment:fragment,internalDate:NOW},confirmation:{confirmed:true as const,messageId:"message-1",fragmentSha256:createHash("sha256").update(fragment).digest("hex"),title:"Submit report",deadlineAt:"2026-07-24T20:00:00Z"}},result=await runtime.importSelectedGmail([action],{consentRevision:1,fetchedAt:NOW},command(0,"gmail-selection"));expect(result.normalizedIds).toHaveLength(1);const state=await runtime.store.load();expect(state.connections.gmail.capabilities).toEqual(["gmail.selected-message.read"]);expect(state.commitments[0]).toMatchObject({title:"Submit report",deadlineAt:"2026-07-24T20:00:00Z"});expect(JSON.stringify(state)).not.toContain(fragment);expect(await runtime.store.loadConnectorToken("gmail")).toBeNull();});

  it("uses bounded exact read-only Google, GitHub, and Linear transports",async()=>{const root=await directory(),seen:{url:string;method:string;body:string}[]=[],fetcher=async(input:string|URL,init?:RequestInit)=>{const url=String(input),method=init?.method??"GET",body=typeof init?.body==="string"?init.body:"";seen.push({url,method,body});if(url.includes("googleapis.com/calendar"))return response({timeZone:"America/Chicago",items:[{id:"g1",summary:"All day",start:{date:"2026-07-23"},end:{date:"2026-07-24"},status:"confirmed",updated:NOW,attendees:[]}],nextPageToken:null});if(url.includes("api.github.com/repos"))return response([{number:7,title:"Issue",state:"open",labels:[],milestone:null,assignees:[],updated_at:NOW}]);if(url==="https://api.linear.app/graphql")return response({data:{issues:{nodes:[{id:"linear-id",identifier:"ENG-7",team:{id:"team"},title:"Linear issue",state:{name:"Todo"},priority:2,estimate:2,cycle:null,dueDate:"2026-07-24",updatedAt:NOW}],pageInfo:{hasNextPage:false,endCursor:null}}}});return response({});};
    const runtime=createLiveConnectorRuntime(env(root),fetcher)!;await runtime.store.initialize(initial());let revision=0;for(const [source,capabilities,payload,consent] of [["google-calendar",["calendar.read"],{accessToken:"google"},1],["github",["task.connect","task.read","task.sync","task.revoke"],{accessToken:"github",installationId:42},1],["linear",["task.connect","task.read","task.sync","task.revoke"],{accessToken:"linear"},1]] as const){await runtime.store.commitConnectorToken({...command(revision,`connect-${source}`),source,envelope:await envelope(runtime,payload),consentRevision:consent,capabilities,connectedAt:NOW});revision+=1;}
    const google=await(await runtime.googleAdapter()).sync({consentRevision:1,fetchedAt:NOW});expect(google.ok&&google.commitments[0]).toMatchObject({startAt:"2026-07-23T05:00:00Z",endAt:"2026-07-24T05:00:00Z"});
    const github=await(await runtime.githubAdapter()).sync({consentRevision:1,fetchedAt:NOW});expect(github.ok&&github.tasks[0]).toMatchObject({source:"github",immutable:true});
    const linear=await(await runtime.linearAdapter()).sync({consentRevision:1,fetchedAt:NOW,estimateRule:{minutesPerPoint:15,maximumPoints:32}});expect(linear.ok&&linear.tasks[0]).toMatchObject({source:"linear",durationMinutes:30,immutable:true});
    expect(seen.find((item)=>item.url.includes("googleapis"))?.url).toContain("singleEvents=true");expect(seen.find((item)=>item.url.includes("api.github.com/repos"))?.method).toBe("GET");expect(seen.find((item)=>item.url==="https://api.linear.app/graphql")).toMatchObject({method:"POST"});expect(seen.at(-1)?.body).toContain("CapacityTasks");expect(JSON.stringify(seen)).not.toMatch(/mutation|PATCH|completeIssue/i);
  });

  it("requests an exact read-only GitHub installation token and rejects response length mismatch",async()=>{const root=await directory(),{privateKey}=generateKeyPairSync("rsa",{modulusLength:2048,privateKeyEncoding:{type:"pkcs8",format:"pem"},publicKeyEncoding:{type:"spki",format:"pem"}}),seen:RequestInit[]=[];const runtime=createLiveConnectorRuntime(env(root,privateKey),async(_input,init)=>{seen.push(init??{});const body=JSON.stringify({token:"installation-token",expires_at:"2026-07-23T16:00:00Z"});return new Response(body,{headers:{"content-length":String(Buffer.byteLength(body)+1)}});})!;await runtime.store.initialize(initial());const started=runtime.githubOAuth!.begin({sessionId:"session-secret",consentRevision:1,expectedRevision:0,commandId:randomUUID(),idempotencyKey:"github-connect"});await expect(runtime.githubOAuth!.consume({state:started.state,sessionId:"session-secret",redirectUri:"http://127.0.0.1:3000/api/v1/oauth/github/callback",installationId:42,setupAction:"install"})).rejects.toThrow("OAUTH_EXCHANGE_FAILED");expect(seen[0]?.body).toBe(JSON.stringify({permissions:{issues:"read",metadata:"read"}}));expect((seen[0]?.headers as Record<string,string>)["x-github-api-version"]).toBe("2026-03-10");expect(await runtime.store.loadConnectorToken("github")).toBeNull();
  });

  it("keeps invalid and partial environment configurations disabled",async()=>{const root=await directory();expect(liveConnectorConfiguration({})).toBeNull();expect(liveConnectorConfiguration({...env(root),CONNECTORS_ENABLED:"0"})).toBeNull();expect(liveConnectorConfiguration({...env(root),CONNECTOR_STATE_PATH:"relative.json"})).toBeNull();});
});
