import { createHash, randomBytes } from "node:crypto";

import type { ConnectorCommand, TokenRepository } from "../../application/connectors";
import { encryptToken, type DataKeyManager } from "../security/crypto";
import { OAuthBoundaryError } from "./one-time";

const bounded=(value:unknown,max:number):value is string=>typeof value==="string"&&value.length>0&&value===value.trim()&&Buffer.byteLength(value)<=max;
const exact=(value:object,keys:readonly string[])=>Object.keys(value).sort().join()===[...keys].sort().join();
const base64url=(value:Uint8Array)=>Buffer.from(value).toString("base64url");
const digest=(value:string)=>createHash("sha256").update(value).digest("base64url");
const INSTALLATION_ENDPOINT="github-app-installation-access-token";
type Timeout=<T>(operation:Promise<T>,milliseconds:number,onTimeout:()=>void)=>Promise<T>;
const systemTimeout:Timeout=async<T>(operation:Promise<T>,milliseconds:number,onTimeout:()=>void)=>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([operation,new Promise<T>((_,reject)=>{timer=setTimeout(()=>{onTimeout();reject(new Error("OAUTH_TIMEOUT"));},milliseconds);})]);}finally{if(timer!==undefined)clearTimeout(timer);}};
export type GitHubInstallationExchangePort=Readonly<{exchange(input:Readonly<{endpoint:typeof INSTALLATION_ENDPOINT;installationId:number;signal:AbortSignal}>):Promise<unknown>}>;
type Pending=Readonly<{sessionHash:string;expiresAt:number;consentRevision:number;command:ConnectorCommand|null}>;

export class GitHubInstallationService{
  private readonly pending=new Map<string,Pending>();
  constructor(private readonly appSlug:string,private readonly redirectUri:string,private readonly exchange:GitHubInstallationExchangePort,private readonly keys:Pick<DataKeyManager,"load">,private readonly tokens:TokenRepository,private readonly clock:Readonly<{now():number}>,private readonly entropy:(bytes:number)=>Uint8Array=(bytes)=>randomBytes(bytes),private readonly withTimeout:Timeout=systemTimeout){if(!/^[a-z0-9](?:[a-z0-9-]{0,98}[a-z0-9])?$/.test(appSlug)||redirectUri!=="http://127.0.0.1:3000/api/v1/oauth/github/callback")throw new OAuthBoundaryError("OAUTH_DISABLED");}
  begin(input:Readonly<{sessionId:string;consentRevision:number;expectedRevision?:number;commandId?:string;idempotencyKey?:string}>){for(const [state,value] of this.pending)if(this.clock.now()>value.expiresAt)this.pending.delete(state);if(!input)throw new OAuthBoundaryError("OAUTH_INVALID");const old=exact(input,["sessionId","consentRevision"]),live=exact(input,["sessionId","consentRevision","expectedRevision","commandId","idempotencyKey"]);if(!old&&!live||!bounded(input.sessionId,512)||!Number.isSafeInteger(input.consentRevision)||input.consentRevision<0||live&&(!Number.isSafeInteger(input.expectedRevision)||input.expectedRevision!<0||!bounded(input.commandId,128)||!bounded(input.idempotencyKey,128))||this.pending.size>=100)throw new OAuthBoundaryError("OAUTH_INVALID");const command=live?Object.freeze({expectedRevision:input.expectedRevision!,commandId:input.commandId!,idempotencyKey:input.idempotencyKey!}):null,state=base64url(this.entropy(32));if(state.length!==43||this.pending.has(state))throw new OAuthBoundaryError("OAUTH_INVALID");const expiresAt=this.clock.now()+600_000;this.pending.set(state,{sessionHash:digest(input.sessionId),expiresAt,consentRevision:input.consentRevision,command});return Object.freeze({schemaVersion:1 as const,authorizationUrl:`https://github.com/apps/${this.appSlug}/installations/new?${new URLSearchParams({state})}`,state,expiresAt:new Date(expiresAt).toISOString()});}
  async consume(input:Readonly<{state:string;sessionId:string;redirectUri:string;installationId:number;setupAction:"install"|"update"}>){if(!input||!exact(input,["state","sessionId","redirectUri","installationId","setupAction"])||!bounded(input.state,100)||!bounded(input.sessionId,512)||input.redirectUri!==this.redirectUri||!Number.isSafeInteger(input.installationId)||input.installationId<=0||!["install","update"].includes(input.setupAction))throw new OAuthBoundaryError("OAUTH_INVALID");const pending=this.pending.get(input.state);if(!pending)throw new OAuthBoundaryError("OAUTH_REPLAY");this.pending.delete(input.state);if(this.clock.now()>pending.expiresAt)throw new OAuthBoundaryError("OAUTH_EXPIRED");if(pending.sessionHash!==digest(input.sessionId))throw new OAuthBoundaryError("OAUTH_INVALID");const controller=new AbortController();let raw:unknown;try{raw=await this.withTimeout(this.exchange.exchange({endpoint:INSTALLATION_ENDPOINT,installationId:input.installationId,signal:controller.signal}),10_000,()=>controller.abort());}catch{throw new OAuthBoundaryError("OAUTH_EXCHANGE_FAILED");}if(!raw||typeof raw!=="object"||Array.isArray(raw)||!exact(raw,["accessToken","expiresAt"]))throw new OAuthBoundaryError("OAUTH_EXCHANGE_FAILED");const token=raw as Record<string,unknown>;if(!bounded(token.accessToken,8_192)||!bounded(token.expiresAt,40)||Number.isNaN(Date.parse(token.expiresAt)))throw new OAuthBoundaryError("OAUTH_EXCHANGE_FAILED");const now=new Date(this.clock.now()).toISOString(),key=await this.keys.load(),capabilities=["task.connect" as const,"task.read" as const,"task.sync" as const,"task.revoke" as const];await this.tokens.save("github",encryptToken(JSON.stringify({accessToken:token.accessToken,installationId:input.installationId,expiresAt:token.expiresAt}),{...key,createdAt:now}),pending.command?{...pending.command,consentRevision:pending.consentRevision,capabilities,connectedAt:now}:undefined);return Object.freeze({schemaVersion:1 as const,source:"github" as const,capabilities:Object.freeze(capabilities),consentRevision:pending.consentRevision,connectedAt:now});}
}
